# Generated by Django 3.1.1 on 2020-09-19 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=50)),
                ('birthdate', models.DateField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 680862))),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=4)),
                ('spouse_name', models.CharField(blank=True, max_length=50)),
                ('spouse_occupation', models.CharField(blank=True, max_length=50)),
                ('no_children', models.IntegerField()),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('created_at', models.DateField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 681861))),
                ('updated_at', models.DateField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 681861))),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customer.person',),
        ),
    ]
