# Generated by Django 3.1.1 on 2020-10-10 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField(default=datetime.datetime(2020, 10, 10, 20, 18, 30, 21995))),
                ('director', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('no_items', models.IntegerField(default=1)),
                ('genres', models.CharField(max_length=255)),
                ('casts', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('created_at', models.DateField(default=datetime.datetime(2020, 10, 10, 20, 18, 30, 22992))),
                ('updated_at', models.DateField(default=datetime.datetime(2020, 10, 10, 20, 18, 30, 22992))),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
