# Generated by Django 3.1.1 on 2020-09-15 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField(default=datetime.datetime(2020, 9, 15, 19, 34, 27, 244478))),
                ('director', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('no_items', models.IntegerField(default=1)),
                ('genres', models.CharField(max_length=255)),
                ('casts', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 15, 19, 34, 27, 245476))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 9, 15, 19, 34, 27, 245476))),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
