# Generated by Django 3.1.1 on 2020-09-16 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 14, 54, 26, 403472)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 14, 54, 26, 403472)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 14, 54, 26, 403472)),
        ),
    ]
