# Generated by Django 3.1.1 on 2020-09-19 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200916_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 677861)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 677861)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 23, 10, 20, 677861)),
        ),
    ]
