# Generated by Django 3.1.1 on 2020-10-09 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200922_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 31, 53, 598794)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 31, 53, 598794)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 31, 53, 598794)),
        ),
    ]
