# Generated by Django 3.1.1 on 2020-10-09 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20201010_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 35, 32, 899856)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 35, 32, 899856)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 35, 32, 899856)),
        ),
    ]
