# Generated by Django 3.1.1 on 2020-10-10 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('order_at', models.DateField(default=datetime.datetime(2020, 10, 10, 20, 18, 30, 27993))),
                ('due_at', models.DateField(default=datetime.datetime(2020, 11, 9, 20, 18, 30, 27993))),
                ('status', models.CharField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('movies', models.ManyToManyField(to='movie.Movie')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
