# Generated by Django 3.1.1 on 2020-10-14 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 13, 19, 7, 55, 795267)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 14, 19, 7, 55, 795267)),
        ),
    ]
