# Generated by Django 3.1.1 on 2020-10-09 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 2, 35, 32, 915897)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 2, 35, 32, 915897)),
        ),
    ]
