# Generated by Django 3.1.1 on 2020-10-09 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201010_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 3, 25, 15, 97426)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 3, 25, 15, 97426)),
        ),
    ]
